# Site settings
title: LING'XIAO | Programmer, Poet, Artist
email: knh190@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Composes poetry and programs in natural & artificial languages,
  ocassionally wood carvings and digital illustrations.
baseurl: ""
url: "https://khn190.github.io"
github_username: KHN190
instagram_username: knh190
# twitter_username: knh190

# Build settings
markdown: kramdown
permalink: pretty
