title: knh190
logo: /assets/img/logo.png
description: I am Lingxiao Yu. Now I live in Shanghai. I am looking for general jobs & commissions. You can send me an email to knh190@hotmail.com or text me on Twitter.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: knh190