# Site settings
title: LING'XIAO | Programmer, Poet, Artist
email: knh190@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Composes poetry and digital interactives in natural & artificial languages,
  ocassionally handcrafts.
baseurl: ""
url: "https://khn190.github.io"
github_username: KHN190
instagram_username: knh190
linkedin_username: lingxiao-yu-587483123
youtube_username: the-rusty-blue
# twitter_username: knh190

# Build settings
markdown: kramdown
permalink: pretty
