# Site settings
title: LING'XIAO | Programmer, Poet, Artist
email: knh190@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  I compose poetry and programs in natural & artificial languages,
  and ocassionally draw digital arts.
baseurl: ""
url: "https://khn190.github.io"
twitter_username: ly5081
github_username:  KHN190

# Build settings
markdown: kramdown
permalink: pretty
